feat(bin): changes
- New shell scripts to handle CSV files: body, cols, extract, header,
  trim
- Better shell script for existing scripts
- Removing redundant scripts: now-playing, search, python-project
- rbw-pinentry-keyring for rbw cli

diff --git a/files/bin/extract b/files/bin/extract
--- a/files/bin/extract
+++ b/files/bin/extract
@@ -1,30 +1,44 @@
 #!/usr/bin/env bash
-#
-# Usage: extract <file>
-# Description: extracts archived files / mounts disk images
-# Note: .dmg/hdiutil is macOS-specific.
-#
-# credit: http://nparikh.org/notes/zshrc.txt
-extract () {
-    if [ -f "$1" ]; then
-        case "$1" in
-            *.tar.bz2)  tar -jxvf "$1"                        ;;
-            *.tar.gz)   tar -zxvf "$1"                        ;;
-            *.bz2)      bunzip2 "$1"                          ;;
-            *.dmg)      hdiutil mount "$1"                    ;;
-            *.gz)       gunzip "$1"                           ;;
-            *.tar)      tar -xvf "$1"                         ;;
-            *.tbz2)     tar -jxvf "$1"                        ;;
-            *.tgz)      tar -zxvf "$1"                        ;;
-            *.zip)      unzip "$1"                            ;;
-            *.ZIP)      unzip "$1"                            ;;
-            *.pax)      pax -r < "$1"                         ;;
-            *.pax.Z)    uncompress "$1" --stdout | pax -r     ;;
-            *.rar)      unrar x "$1"                          ;;
-            *.Z)        uncompress "$1"                       ;;
-            *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
-        esac
-    else
-        echo "'$1' is not a valid file"
-    fi
-}
+# unpack: Extract common file formats
+
+# Dependencies: unrar, unzip, p7zip-full
+
+# Author: Patrick Brisbin
+# From: http://linuxtidbits.wordpress.com/2009/08/04/week-of-bash-scripts-extract/
+
+# Display usage if no parameters given
+if [[ -z "$@" ]]; then
+	echo " ${0##*/} <archive> - extract common file formats)"
+	exit
+fi
+
+# Required program(s)
+req_progs=(7z unrar unzip)
+for p in ${req_progs[@]}; do
+	hash "$p" 2>&- || \
+	{ echo >&2 " Required program \"$p\" not installed."; exit 1; }
+done
+
+# Test if file exists
+if [ ! -f "$@" ]; then
+	echo "File "$@" doesn't exist"
+	exit
+fi
+
+# Extract file by using extension as reference
+case "$@" in
+	*.7z ) 7z x "$@" ;;
+	*.tar.bz2 ) tar xvjf "$@" ;;
+	*.bz2 ) bunzip2 "$@" ;;
+	*.deb ) ar vx "$@" ;;
+	*.tar.gz ) tar xvf "$@" ;;
+	*.gz ) gunzip "$@" ;;
+	*.tar ) tar xvf "$@" ;;
+	*.tbz2 ) tar xvjf "$@" ;;
+	*.tar.xz ) tar xvf "$@" ;;
+	*.tgz ) tar xvzf "$@" ;;
+	*.rar ) unrar x "$@" ;;
+	*.zip ) unzip "$@" ;;
+	*.Z ) uncompress "$@" ;;
+	* ) echo " Unsupported file format" ;;
+esac
